defaults: &defaults
  working_directory: ~/repo

version: 2
jobs:
  build:
    <<: *defaults
    docker:
      - image: circleci/node:4.8

    steps:
      - checkout

      - run:
          name: Install Meteor
          command: if [ ! -e "$HOME/.meteor/meteor" ]; then curl https://install.meteor.com | sed s/--progress-bar/-sL/g | /bin/sh; fi

      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}

      - run:
          name: Lint
          command: |
            meteor npm install
            meteor npm run lint
            meteor npm run testunit
            meteor npm run stylelint

      - run:
          name: Build Rocket.Chat
          command: |
            set +e
            meteor add rocketchat:lib
            set -e
            meteor build --server-only --directory /tmp/build-test
            cd /tmp/build-test/bundle/programs/server
            npm install

      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
            - ./.meteor
            - /home/circleci/.meteor

      - persist_to_workspace:
          root: /tmp/
          paths:
            - build-test

  test-with-oplog:
    <<: *defaults
    docker:
      - image: circleci/node:4.8
        environment:
          TEST_MODE: "true"
      - image: circleci/mongo:3.4
        command: [mongod, --smallfiles, --replSet rs0]
        environment:
          MONGO_URL: mongodb://localhost:27017/testwithoplog
          MONGO_OPLOG_URL: mongodb://localhost:27017/local

    steps:
      - attach_workspace:
          at: /tmp/build-test

      - checkout

      - run:
          name: Install Meteor
          command: if [ ! -e "$HOME/.meteor/meteor" ]; then curl https://install.meteor.com | sed s/--progress-bar/-sL/g | /bin/sh; fi

      - run:
          name: Install MongoDB Client
          command: |
            sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 0C49F3730359A14518585931BC711F9BA15703C6
            echo "deb [ arch=amd64 ] http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.4 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-3.4.list
            sudo apt-get update
            sudo apt-get install -y mongodb-org-shell

      - run:
          command: |
            mongo --eval 'rs.initiate({_id:"rs0", members: [{"_id":1, "host":"localhost:27017"}]})'
            meteor npm test

  test-without-oplog:
    <<: *defaults
    docker:
      - image: circleci/node:4.8
        environment:
          TEST_MODE: "true"
      - image: circleci/mongo:3.4
        command: [mongod, --smallfiles]
        environment:
          MONGO_URL: mongodb://localhost:27017/testwithoutoplog

    steps:
      - attach_workspace:
          at: /tmp/build-test

      - checkout

      - run:
          name: Install Meteor
          command: if [ ! -e "$HOME/.meteor/meteor" ]; then curl https://install.meteor.com | sed s/--progress-bar/-sL/g | /bin/sh; fi

      - run:
          command: |
            meteor npm test

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - test-with-oplog:
          requires:
            - build
      - test-without-oplog:
          requires:
            - build
